# Generated by Django 4.0 on 2022-01-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('item_img', models.ImageField(upload_to='media')),
                ('item_desc', models.TextField()),
                ('place', models.TextField()),
            ],
        ),
    ]
