# Generated by Django 4.0 on 2022-01-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='claim',
            field=models.BooleanField(default=False),
        ),
    ]
