# Generated by Django 4.0 on 2022-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0002_lostitem_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
